### ISSUE TITLE
[proposal] New Heroic Games Launcher Website

### ISSUE THREAD

**Issue by alinpr18** [Heroic-Games-Launcher/heroic-website#12]
Built with Next.js 13 + Tailwindcss

Github Repository: https://github.com/alinpr18/heroic-website-nextjs13

Live demo: https://heroic-website-nextjs13.vercel.app/

Pull requeast and feedback are welcome

**Comment by flavioislima** [comment]
The website looks nice, not too different though.
Most of the links needs to be fixed and the screenshots updated as well. 

Would be good to have a PR against our repo so we could test and improve over it. 👍

**Comment by alinpr18** [comment]
Ready! https://github.com/Heroic-Games-Launcher/heroic-website/pull/14
