### ISSUE TITLE
License

### ISSUE THREAD

**Issue by JakobDev** [Heroic-Games-Launcher/heroic-website#3]
I'm currently trying to make a little Website for my own App, but I don't have much Web Development Experience. Can I use your Website as Base and modify it for my needs? This Repo doesn't have I License, so I better ask.

**Comment by flavioislima** [comment]
@JakobDev sure man, feel free to do it 👍🏽 

sorry for the late response, for some reason I don't get emails about issues on this repo, or I just missed it.
